language: cpp
sudo: true
dist: trusty

compiler:
    - g++

#Build steps
before_install:
    - sudo apt-get install libsdl-mixer1.2-dev -y

script:
    - mkdir build
    - cd build
    - cmake ..
    - make